import type { SanitizedUser } from '@store-mgmt/api-common';
import {
  RoleHelpers,
  USER_ROLES,
  WarehouseScopeViolationError,
  type IWarehouseOperatorRepository,
} from '@store-mgmt/domain';

/**
 * `true` only for a caller whose access comes SOLELY from `sales_agent` —
 * not from `owner`, `admin` or `sales_operator`.
 *
 * The distinction matters because scoping is about what a caller may SEE, and
 * an owner who also happens to hold the agent bit still supervises the whole
 * company. Scoping them to their own rows would hide their staff's sales from
 * them.
 *
 * Lives here, on its own, because two controllers now need it. Two copies of a
 * predicate that decides who can read whose earnings is exactly the kind of
 * duplication that drifts apart quietly.
 */
export function isScopedSalesAgent(user: SanitizedUser): boolean {
  return (
    RoleHelpers.hasRole(user.roles, USER_ROLES.sales_agent) &&
    !RoleHelpers.hasRole(user.roles, USER_ROLES.owner) &&
    !RoleHelpers.hasRole(user.roles, USER_ROLES.admin) &&
    !RoleHelpers.hasRole(user.roles, USER_ROLES.sales_operator)
  );
}

/**
 * `true` only for a caller whose access comes SOLELY from
 * `warehouse_operator` — `owner`/`admin`/`sales_operator` supervise the whole
 * company and are never scoped to one warehouse.
 *
 * Lives here, next to `isScopedSalesAgent`, for the same reason: more than one
 * door now needs it. `POST /orders/:id/deliver` and
 * `POST /delivery/assignments/:id/deliver` drive the SAME transition on the
 * same order, consuming the same stock and firing the same commission
 * accrual — a copy of this rule that only one of them applied is not a
 * narrower grant, it is a bypass.
 */
export function isScopedWarehouseOperator(user: SanitizedUser): boolean {
  return (
    RoleHelpers.hasRole(user.roles, USER_ROLES.warehouse_operator) &&
    !RoleHelpers.hasRole(user.roles, USER_ROLES.owner) &&
    !RoleHelpers.hasRole(user.roles, USER_ROLES.admin) &&
    !RoleHelpers.hasRole(user.roles, USER_ROLES.sales_operator)
  );
}

/**
 * A warehouse id, or a function that produces one only if it is needed.
 *
 * The lazy form exists so a caller that would have to PAY for the id (an
 * extra read) can hand over the means of getting it instead of deciding for
 * itself whether the rule applies. `markDelivered` used to wrap this call in
 * its own copy of `isScopedWarehouseOperator` to avoid that read, which put
 * the RULE in one place and the DECISION TO APPLY IT in two — widening the
 * rule later would silently not have taken effect there.
 */
export type WarehouseIdSource = string | (() => Promise<string>);

/**
 * The ONE warehouse-scope assertion, with ONE call shape. A scoped
 * `warehouse_operator` may only act on orders belonging to their OWN
 * warehouse; anyone else passes through untouched, issues no extra read, and
 * never resolves a lazy `warehouseId`.
 *
 * Throws the DOMAIN `WarehouseScopeViolationError`, never a NestJS
 * `ForbiddenException`: this is called from `DeliveryService`, whose every
 * other failure is a domain error its controllers map. Each controller maps
 * this one to 403 (`OrderController` included — its observable behavior,
 * status and message alike, is unchanged).
 */
export async function assertWarehouseScope(
  user: SanitizedUser,
  warehouseId: WarehouseIdSource,
  warehouseOperatorRepository: IWarehouseOperatorRepository,
): Promise<void> {
  if (!isScopedWarehouseOperator(user)) {
    return;
  }
  const resolvedWarehouseId = typeof warehouseId === 'string' ? warehouseId : await warehouseId();
  const operator = await warehouseOperatorRepository.findByUserId(user.id);
  if (!operator || operator.warehouseId !== resolvedWarehouseId) {
    throw new WarehouseScopeViolationError(resolvedWarehouseId);
  }
}

/**
 * The list counterpart of `assertWarehouseScope`: `null` when the caller is
 * not warehouse-scoped (see everything), otherwise the one warehouse they may
 * see. `undefined` operator row -> an id that matches nothing, so a
 * `warehouse_operator` with no `WarehouseOperator` detail row sees an EMPTY
 * list rather than the whole tenant — the same fail-closed choice
 * `OrderController.scopeToOperatorWarehouse` makes by returning `[]`.
 */
export async function resolveWarehouseScopeFilter(
  user: SanitizedUser,
  warehouseOperatorRepository: IWarehouseOperatorRepository,
): Promise<string | null> {
  if (!isScopedWarehouseOperator(user)) {
    return null;
  }
  const operator = await warehouseOperatorRepository.findByUserId(user.id);
  return operator?.warehouseId ?? NO_WAREHOUSE;
}

/**
 * A syntactically valid uuid that no `warehouse` row can hold (the all-zero
 * uuid is never generated by `gen_random_uuid()`). Used as the scope filter
 * for an operator with no detail row, so the query returns nothing instead of
 * the filter being silently dropped.
 */
export const NO_WAREHOUSE = '00000000-0000-0000-0000-000000000000';
