import type { SeededProduct } from '../domain/types';
import { deriveCommission, type CommissionRule } from './commission-map';

export interface CommissionReviewRow {
  id: string;
  name: string;
  category: string;
  price: number;
  costUSD: number;
  commissionMN: number;
  rule: CommissionRule;
  /** True when `rule` is `category-default` or `catch-all` — needs human sign-off. */
  isFallback: boolean;
}

const FALLBACK_RULES: CommissionRule[] = ['category-default', 'catch-all'];

/**
 * Builds the reviewable product -> commissionMN table (spec: "Reviewable
 * Commission Assignment Output"). Re-derives the rule per product (cheap,
 * pure) rather than threading it through `SeededProduct`, so the surface can
 * be regenerated from any `SeededProduct[]` without extra plumbing.
 */
export function buildCommissionReviewTable(products: SeededProduct[]): CommissionReviewRow[] {
  return products.map((product) => {
    const { rule } = deriveCommission(product.name, product.categoryId);
    return {
      id: product.id,
      name: product.name,
      category: product.categoryId,
      price: product.price,
      costUSD: product.costUSD,
      commissionMN: product.commissionMN,
      rule,
      isFallback: FALLBACK_RULES.includes(rule),
    };
  });
}

/** Renders the review table as a markdown table, flagging fallback rows with ⚠. */
export function formatCommissionTableMarkdown(rows: CommissionReviewRow[]): string {
  const header = '| id | name | category | price | costUSD | commissionMN | rule |';
  const divider = '| --- | --- | --- | --- | --- | --- | --- |';
  const lines = rows.map((row) => {
    const flag = row.isFallback ? ' ⚠' : '';
    return `| ${row.id} | ${row.name}${flag} | ${row.category} | ${row.price} | ${row.costUSD} | ${row.commissionMN} | ${row.rule} |`;
  });
  return [header, divider, ...lines].join('\n');
}

/**
 * Full committed artifact (`app/seed/__snapshots__/commission-table.md`):
 * a short human-readable header + the markdown table. Kept separate from
 * `formatCommissionTableMarkdown` so the dev route can render just the table.
 */
export function formatReviewTableDocument(rows: CommissionReviewRow[]): string {
  const fallbackCount = rows.filter((row) => row.isFallback).length;
  const header = [
    '# Commission Review Table',
    '',
    'Generated by `app/seed/review-table.ts` from the 99-product catalog (`app/data/catalog.json`).',
    'Rows flagged ⚠ resolved via `category-default` or the `1000` catch-all and need human sign-off.',
    '',
    `Total products: ${rows.length} | Fallback rows: ${fallbackCount}`,
    '',
  ].join('\n');
  return `${header}${formatCommissionTableMarkdown(rows)}\n`;
}
